### ISSUE TITLE
how to remove EventListener

### ISSUE THREAD

**Issue by Emilios1995** [alexkendall/react-native-bluetooth-cross-platform#12]
Is it possible to remove event listeners?

**Comment by alexkendall** [comment]
@Emilios1995 Will add this feature.

**Comment by alexkendall** [comment]
@Emilios1995 
My latest commit a3a11a5d1f339640bba639ce5f70198640635b65 should make the listeners removable. I'll update the readme with directions how to.

**Comment by Emilios1995** [comment]
Thanks!
