### ISSUE TITLE
Sample project required to understand

### ISSUE THREAD

**Issue by Jasbir23** [alexkendall/react-native-bluetooth-cross-platform#2]
What is static library? 
Mentioning the specific files to be added would make it a lot easier to use the package.

**Comment by alexkendall** [comment]
@Jasbir23 Looking into this right now. I haven't been able to touch the library in a while due to how busy I am but i'll make sure to get everything working and easy to use by next week.

**Comment by Jasbir23** [comment]
@alexkendall please update the readme too with the manual installation steps. Great help. Thank you!!

**Comment by Jasbir23** [comment]
Thanks @alexkendall. The library works now. Great job with it!! Closing this issue with this :)

**Comment by x5c** [comment]
@Jasbir23 can you share how it work ?
