### ISSUE TITLE
How to complete step two of the iOS installation process

### ISSUE THREAD

**Issue by Progoogler** [alexkendall/react-native-bluetooth-cross-platform#31]
> 2.) add files in './node_modules/react-native-bluetooth-cross-platform/ios/react-native-bluetooth-cross-platform' to project. When XCode asks to create bridging header, click YES. Delete the bridging header XCode generates for you.

Sorry for the noob question. Xcode has always been a foreign beast for me to tame. Can someone please quickly explain how I would add the files from `./node_modules/react-native-bluetooth-cross-platform/ios/react-native-bluetooth-cross-platform` to my project?

Does this mean that I should create a `ReactNativeBlueToothCrossPlatform.xcodeproj` in my project's `library` and put all those files in that  `xcodeproject`? If not, where should I place all those files inside my "project"?

Many thanks in advance!

**Comment by Progoogler** [comment]
Haha... jk. This is embarrassing.. All I needed to do was go into File -> Add Files to "App" -> Select all the files within that folder and complete the rest of the installation. Wish I could delete this "issue". Anyway, this will be for public display and might save someone else a crimson blush.

**Comment by rynatk** [comment]
I was also stuck on this one @Friendly-Robot. I got around it by dragging and dropping the files from my finder into the Xcode application.
