### ISSUE TITLE
IOS project wont run after npm support

### ISSUE THREAD

**Issue by Jasbir23** [alexkendall/react-native-bluetooth-cross-platform#4]
Hey alex,
I installed the library via nmp. The android project works fine. Having trouble with the ios part. Having completed all the installation steps, the app does not run with following error. Hoping for a quick fix on this :)

![screen shot 2016-11-29 at 7 39 29 pm](https://cloud.githubusercontent.com/assets/22442136/20743496/c1805004-b6fc-11e6-9083-f44f731ef1a2.png)

Also this is what my Xcode project looks like..

![screen shot 2016-11-29 at 7 44 13 pm](https://cloud.githubusercontent.com/assets/22442136/20743536/f359f8dc-b6fc-11e6-8854-921b5e30e679.png)

P.S. All was working fine before the npm support was added

**Comment by alexkendall** [comment]
Hey Jasbir,

Thanks for letting me know!. I'll take a look tonight and get this issue
resolved.


Best,
Alex

*Alex Harrison*
Phone*  616-648-2833*
Email   *alex@alexkharrison.com <alex@alexkharrison.com>*
Web     alexkharrison.com

**Comment by alexkendall** [comment]
@Jasbir23 Sorry about not getting to this sooner but I've been absolutely swamped at work. I should be able to get to it sometime this week. We're you able to find a work around to the issue?

**Comment by Jasbir23** [comment]
@alexkendall No, I have been using the previous version of this library. Great to hear though  :)

**Comment by Jasbir23** [comment]
Hey @alexkendall,
 Hope things are better at work :) ,
Any chance you found the problem here?

**Comment by alexkendall** [comment]
@Jasbir23 Taking a look tonight.

**Comment by Jasbir23** [comment]
@alexkendall Great 👍

**Comment by alexkendall** [comment]
@Jasbir23 Just released a new version with an updated README but haven't had much time to test, so use with caution.

**Comment by iotashan** [comment]
I fixed the readme and sent a PR.

**Comment by alexkendall** [comment]
@iotashan Thanks. Closing this after #7.
