### ISSUE TITLE
Help me install...

### ISSUE THREAD

**Issue by jongmin92** [alexkendall/react-native-bluetooth-cross-platform#5]
I found 'react-native-bluetooth-cross-platform' when searching for Bluetooth advertise function.
I'm having trouble installing react-native-bluetooth-cross-platform.

(1) Installation (iOS)
I would really appreciate if you could attach **screenshots** for steps 3, 4, 5, and 6.
(2) Installation (Android)
I tried the manual but got a **'can not find symbol' Error.**

My react-native-cli: 2.0.1
      react-native: 0.39.2

And finally one more question. I tried downloading and running the 'Solidarity' app, but there was no connect between Android and iOS. If you are using 'react-native-bluetooth-cross-platform', is it possible to **connect between Android and iOS**?

Sorry for the simple but cumbersome question. I would appreciate any help.

**Comment by HongSeokHwan** [comment]
me too...

**Comment by Jasbir23** [comment]
@kdhx92 you are using wifi to connect ios and android devices?

**Comment by kdhx92** [comment]
@Jasbir23 I followed the manual, but I can not build Android.

**Comment by alexkendall** [comment]
@kdhx92 @HongSeokHwan Ill take a look this weekend

**Comment by alexkendall** [comment]
@jongmin92 Can you try installing for Android with the new instructions?

**Comment by jongmin92** [comment]
@alexkendall I'm sorry for late reply. Thank you. Solved!

**Comment by alexkendall** [comment]
Closing this after integration of #6 and #7.
