### ISSUE TITLE
Issue on RN 0.42.0

### ISSUE THREAD

**Issue by Unforgiven-wanda** [alexkendall/react-native-bluetooth-cross-platform#9]
Hello,
after following the install procedure for Android, I get the following error:
![sa](https://cloud.githubusercontent.com/assets/4499783/23612395/9c479ea8-027b-11e7-9dc4-f90167a43b2b.png)

The only notable thing is inside my `build.gradle` file, which is configured like so:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "$rootDir/../node_modules/react-native/android" }
        maven { url 'https://dl.bintray.com/underdark/android/' }
    }
}

```

Does the issue stem from RN 0.42, or is it something else?
Thank you.

**Comment by Unforgiven-wanda** [comment]
Okay, I must be really tired because I haven't even bothered to read the error, which is that there is no Bluetooth device since i'm on an emulator. Sorry :/
Closing and going home...

**Comment by virl** [comment]
@Unforgiven-wanda Thanks for bug report anyway, although it is probably issue of my native library ([https://github.com/udark/underdark-android/]), not these React bindings.
It's already in the plans to not crash the app when you create the bluetooth transport on device without Bluetooth support. :)
